name: java & python build and deploy
on: 
  push:
    branches:
      - main .
  pull_request:
    branches:
      - main .
jobs: 
  build:
    runs-on: Ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: >
        echo "${{ secrets.DOCKERPW }}" | docker login -u "skandasbhat"
        --password-stdin

        docker image build -t skandasbhat/python:latest .

        docker push skandasbhat/python:latest
    - name: run Image
      run: >
        echo "${{ secrets.DOCKERPW }}" | docker login -u "skandasbhat"
        --password-stdin

        docker pull skandasbhat/python:latest 

        docker run skandasbhat/python:latest
